apiVersion: v1
kind: ConfigMap
metadata:
  name: mdforge-config
  namespace: default
data:
  APP_NAME: "mdForge"
  VERSION: "1.0.0"
  DEBUG: "false"
  MAX_FILE_SIZE_MB: "100"
  API_V1_STR: "/api/v1"
  ENABLE_AI_PROCESSING: "true"
  OPENAI_BASE_URL: "http://ollama-service:11434"  # Your local ollama
