apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdforge
  namespace: default
  labels:
    app: mdforge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mdforge
  template:
    metadata:
      labels:
        app: mdforge
    spec:
      containers:
      - name: mdforge
        image: onegaionegai/mdforge:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: mdforge-config
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mdforge-secrets
              key: openai-api-key
              optional: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: mdforge-secrets
  namespace: default
type: Opaque
stringData:
  openai-api-key: "your-openai-api-key-here"
  anthropic-api-key: "your-anthropic-api-key-here"
  google-api-key: "your-google-api-key-here"
